name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  BACKEND_HOME: ./vehicle

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: "${{ env.BACKEND_HOME }}/pom.xml" # optional
      - name: Build with Maven
        working-directory: ${{ env.BACKEND_HOME }}
        run: mvn -B package
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        working-directory: ${{ env.BACKEND_HOME }}
        run: |
          ls 
          ls ./target
          pwd
          env
      - name: Build docker image
        working-directory: ${{ env.BACKEND_HOME }}
        run: |
          docker build -t hello --file ./src/main/docker/Dockerfile .
          docker image ls
